---

- name: List clusters
  command: pg_lsclusters -j
  register: postgresql_ls_clusters

- name: Initialize cluster information variable
  set_fact:
    postgresql_cluster_info: "{{ postgresql_cluster_info | default({}) }}"

- name: Transform cluster information into a dict
  set_fact:
    postgresql_cluster_info: "{{ postgresql_cluster_info | combine ({ item.version : item }) }}"
  with_items:
    "{{ postgresql_ls_clusters.stdout | from_json }}"


